trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'
pr:
  branches:
    include:
    - master

resources:
  repositories:
  - repository: PSRepositoryReleaseManager
    type: github
    name: theohbrothers/PSRepositoryReleaseManager
    endpoint: myserviceconnection                   # Check for your 'Type: Github' connection under 'Project Settings' > 'Service connections'
    ref: refs/tags/vx.x.x

stages:
- stage: release
  displayName: Release
  jobs:
  - job: linux_container
    displayName: '[Linux] [Container] PowerShell Core'
    pool:
      vmImage: ubuntu-latest
    container: theohbrothers/docker-powershell:7.2-ubuntu-22.04-git
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/generate.yml@PSRepositoryReleaseManager
    - template: templates/azure-pipelines/entrypoint/release.yml@PSRepositoryReleaseManager
