trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'
pr:
  branches:
    include:
    - master

resources:
  repositories:
  - repository: PSRepositoryReleaseManager
    type: github
    name: theohbrothers/PSRepositoryReleaseManager
    endpoint: myserviceconnection                   # Check for your 'Type: Github' connection under 'Project Settings' > 'Service connections'
    ref: refs/tags/vx.x.x

stages:
- stage: release
  displayName: Release
  jobs:
  - job: windows_powershell_5_1
    displayName: '[Windows] PowerShell 5.1'
    pool:
      vmImage: windows-latest
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/powershell/generate.yml@PSRepositoryReleaseManager
    - template: templates/azure-pipelines/entrypoint/powershell/release.yml@PSRepositoryReleaseManager
